name: mtd
dependencies:
  - python=3.4
  - ipython-notebook
  - bokeh
  - requests
  - pandas
  - beautiful-soup
  - nltk
  - scikit-learn
  - pip:
    - oauth2
    - Click
    - flask
    - flask-restful
    - feedparser
